openapi: 3.0.1
info:
  title: printorder
  description: Print Order
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: SnipCart
    description: For snipcart webhooks
  - name: CloudPRNT
    description: For cloudprnt specification.
  - name: Specification
    description: The swagger API specification
paths:
  /snipcart:
    post:
      tags:
        - SnipCart
      description: des1
      responses:
        200:
          description: works
          content:
            application/json:
              schema:
                type: object
  /cloudprnt:
    delete:
      tags:
        - CloudPRNT
      description: Indicate order processing is complete.
      responses:
        200:
          description: works
          content:
            application/json:
              schema:
                type: object
      parameters:
        - name: t
          in: query
          description: The t of the example to retrieve
          required: true
          schema:
            type: string
    post:
      tags:
        - CloudPRNT
      description: The polling endpoint for printer.
      responses:
        200:
          description: works
          content:
            application/json:
              schema:
                type: object
      parameters:
        - name: t
          in: query
          description: The t of the example to retrieve
          required: true
          schema:
            type: string
    get:
      tags:
        - CloudPRNT
      description: The job fetching endpoint.
      parameters:
        - name: uid
          in: query
          description: The uid of the example to retrieve
          required: true
          schema:
            type: string
        - name: type
          in: query
          description: The media type
          required: true
          schema:
            type: string
        - name: mac
          in: query
          description: The mac address of the printer
          required: true
          schema:
            type: string
        - name: token
          in: query
          description: The uid of the example to retrieve
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: hey
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    Example:
      type: object
      properties:
        id:
          type: integer
          example: 3
        name:
          type: string
          example: example 3
    Error:
      type: object
      additionalProperties: true

    ExampleBody:
      title: example
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: no_stress
